apiVersion: v1
kind: Deployment
metadata:
  name: click-py
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: click-py
  template:
    metadata:
      labels:
        app: click-py
